version: '2' # required to adjust maintainability checks

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 50
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 45
  identical-code:
    enabled: true
    config:
      threshold: 45

exclude_patterns:
  - 'config/'
  - 'supabase/'
  - 'dist/'
  - 'public/'
  - 'tools/'
  - 'coverage/'
  - '**/node_modules/'
  - '**/.next/'
  - '**/jest.config.ts'
  # we need test files to be explicit as much as possible
  # avoiding DRY for tests tends make debugging harder,
  # and also increases cognitive complexity
  - '**/*.spec.ts'
  # exclude testutils
  - '**/*.faker.ts'
  - '**/*.msw.ts'
