name: Dev

on:
  push:
    # run on all branches except main
    branches-ignore: [main]
  # Option to execute manually
  workflow_dispatch:

# cancel duplicate
concurrency:
  group: dev-cicd
  cancel-in-progress: true

jobs:
  db-migration:
    name: DB Migration local -> dev
    runs-on: ubuntu-latest
    environment:
      name: Dev
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GA_PAT }}
      - name: Setup supabase-cli
        uses: supabase/setup-cli@v1
        with:
          version: 1.33.0
      - name: Supabase migration
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase db push

  create-pull-request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ env.branch_name }}
      pr_num: ${{ steps.create-pull-request.outputs.pull-request-number }}
    steps:
      - name: Get main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GA_PAT }}
      - name: Extract branch name
        shell: bash
        run: echo "branch_name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        id: extract-branch
      - name: Get PR label
        # This command just trims chars before "/" e.g. "feature/one" -> "feature"
        run: echo "LABEL=$(s=$(git rev-parse --abbrev-ref HEAD) && echo "${s%%/*}")" >> $GITHUB_ENV
        id: get-pr-label
      - name: Get PR title
        run: echo "PR_TITLE=$(node tools/scripts/get-pr-title.js ${{ env.branch_name }})" >> $GITHUB_ENV
        id: get-pr-title
      - name: GPG Verification
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          fingerprint: 'A00EC0908EBB330097F9F9F018E545E55315C616'
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_push_gpgsign: true
      - name: Reset main branch into feature branch
        run: |
          git checkout main
          git fetch origin ${{ env.branch_name }}:${{ env.branch_name }}
          git reset --hard ${{ env.branch_name }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        id: create-pull-request
        with:
          token: ${{ secrets.GA_PAT }}
          committer: John Ballesteros <johnshift.dev@gmail.com>
          branch: ${{ env.branch_name }}
          title: '${{ env.PR_TITLE }}'
          labels: '${{ env.LABEL }}'
          assignees: johnshift
          body: ':zap: Automated PR'
      - name: Enable Pull Request Automerge
        if: steps.create-pull-request.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GA_PAT }}
          pull-request-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
          merge-method: squash

  get-affected:
    name: Get NX Affected Libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GA_PAT }}
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Get test affected libs
        run: echo "test_libs=$(node tools/scripts/get-affected-libs.js test ${{ secrets.LATEST_TAG_SHA }} ${{ github.sha }})" >> $GITHUB_ENV
      - name: Echo Test Affected Libraries
        run: echo "affected test libs = ${{ env.test_libs }}"
    outputs:
      test_libs: ${{ env.test_libs }}

  run-tests:
    name: ${{ matrix.projectName }}
    runs-on: ubuntu-latest
    needs: [get-affected]
    if: ${{ fromJson(needs.get-affected.outputs.test_libs)[0] }}
    strategy:
      matrix:
        projectName: ${{ fromJson(needs.get-affected.outputs.test_libs ) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GA_PAT }}
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Unit Test Affected by Release
        # Note: skip cache, otherwise tests will replay results from local machines
        #       which results to incorrect coverage paths (local and ci paths are structured differently)
        run: pnpm nx test ${{ matrix.projectName }} --codeCoverage --skip-nx-cache

      - name: Move shard coverage
        run: mv $(find coverage -name coverage-final.json) coverage/${{matrix.projectName}}.json

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-artifacts
          path: coverage/

  test-report:
    name: Test Report
    runs-on: ubuntu-latest
    needs: [create-pull-request, run-tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GA_PAT }}

      - name: Download coverage from jest shards
        uses: actions/download-artifact@v3
        with:
          name: coverage-artifacts
          path: coverage

      - name: Merge Code Coverage
        run: npx nyc merge coverage/ merged-output/merged-coverage.json

      - name: Generate coverage report
        run: npx nyc report -t merged-output --report-dir merged-output --reporter lcov

      - name: Upload coverage to codeclimate
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/merged-output/lcov.info:lcov

  chromatic:
    name: Publish Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GA_PAT }}
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          externals: 'public/**'
          traceChanged: 'expanded'

  dev-deploy:
    name: Dev Deploy
    runs-on: ubuntu-latest
    environment:
      name: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GA_PAT }}

      - name: Deploy to Vercel
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: --prod

  e2e-tests:
    name: Web E2E
    runs-on: ubuntu-latest
    needs: [dev-deploy]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GA_PAT }}
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Cypress e2e
        uses: cypress-io/github-action@v5
        env:
          E2E_BASE_URL: https://lihim-dev.vercel.app
        with:
          browser: chrome
          wait-on: https://lihim-dev.vercel.app
          install: false # already installed
          command: pnpm e2e --skip-nx-cache

  final-check:
    name: Final Check
    runs-on: ubuntu-latest
    needs: [test-report, e2e-tests, chromatic]
    # Always run even any of needs was skipped/failed/canceled
    if:
      always()
      # needs.*.result == 'success' &&
    steps:
      - name: Fail on skipped/cancelled/failure
        if: |
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'cancelled')||
          contains(needs.*.result, 'skipped')
        run: exit 1
      - run: echo "All checks passed"
